import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const DATA_URL = "https://geo.datav.aliyun.com/areas_v3/bound";

const PROVINCES = [
  { adcode: "110000", name: "北京市" },
  { adcode: "120000", name: "天津市" },
  { adcode: "130000", name: "河北省" },
  { adcode: "140000", name: "山西省" },
  { adcode: "150000", name: "内蒙古自治区" },
  { adcode: "210000", name: "辽宁省" },
  { adcode: "220000", name: "吉林省" },
  { adcode: "230000", name: "黑龙江省" },
  { adcode: "310000", name: "上海市" },
  { adcode: "320000", name: "江苏省" },
  { adcode: "330000", name: "浙江省" },
  { adcode: "340000", name: "安徽省" },
  { adcode: "350000", name: "福建省" },
  { adcode: "360000", name: "江西省" },
  { adcode: "370000", name: "山东省" },
  { adcode: "410000", name: "河南省" },
  { adcode: "420000", name: "湖北省" },
  { adcode: "430000", name: "湖南省" },
  { adcode: "440000", name: "广东省" },
  { adcode: "450000", name: "广西壮族自治区" },
  { adcode: "460000", name: "海南省" },
  { adcode: "500000", name: "重庆市" },
  { adcode: "510000", name: "四川省" },
  { adcode: "520000", name: "贵州省" },
  { adcode: "530000", name: "云南省" },
  { adcode: "540000", name: "西藏自治区" },
  { adcode: "610000", name: "陕西省" },
  { adcode: "620000", name: "甘肃省" },
  { adcode: "630000", name: "青海省" },
  { adcode: "640000", name: "宁夏回族自治区" },
  { adcode: "650000", name: "新疆维吾尔自治区" },
  { adcode: "710000", name: "台湾省" },
  { adcode: "810000", name: "香港特别行政区" },
  { adcode: "820000", name: "澳门特别行政区" },
];

// 直辖市、港澳台：作为单个地级单位
const SINGLE_ENTRIES = new Set([
  "110000", "120000", "310000", "500000",
  "710000", "810000", "820000",
]);

async function fetchJson(url) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Fetch failed: ${url} → ${res.status}`);
  return res.json();
}

async function main() {
  const allFeatures = [];
  const divisionsData = [];
  const provinceNames = {};

  for (const prov of PROVINCES) {
    provinceNames[prov.adcode] = prov.name;
    const isSingle = SINGLE_ENTRIES.has(prov.adcode);

    try {
      const suffix = isSingle ? ".json" : "_full.json";
      const url = `${DATA_URL}/${prov.adcode}${suffix}`;
      console.log(`Fetching ${prov.name} (${prov.adcode})...`);
      const geojson = await fetchJson(url);

      if (isSingle) {
        // 直辖市/港澳台：用省级 Feature 作为单条目
        const feature = geojson.features[0];
        if (feature) {
          const entry = {
            adcode: String(feature.properties.adcode),
            name: prov.name,
            province: prov.name,
            provinceAdcode: prov.adcode,
          };
          allFeatures.push(feature);
          divisionsData.push(entry);
        }
      } else {
        // 普通省份：提取 level=city 的 features
        const cityFeatures = geojson.features.filter(
          (f) => f.properties.level === "city",
        );
        for (const feature of cityFeatures) {
          const props = feature.properties;
          const entry = {
            adcode: String(props.adcode),
            name: props.name,
            province: prov.name,
            provinceAdcode: prov.adcode,
          };
          allFeatures.push(feature);
          divisionsData.push(entry);
        }
        console.log(`  → ${cityFeatures.length} prefectural divisions`);
      }
    } catch (err) {
      console.error(`  ✗ Failed: ${err.message}`);
    }
  }

  // 合并 GeoJSON
  const mergedGeoJson = {
    type: "FeatureCollection",
    features: allFeatures,
  };

  // 写入 public/china-prefecture.json
  const publicDir = resolve(ROOT, "public");
  await mkdir(publicDir, { recursive: true });
  await writeFile(
    resolve(publicDir, "china-prefecture.json"),
    JSON.stringify(mergedGeoJson, null, 2),
  );
  console.log(`\nGeoJSON saved: ${allFeatures.length} features`);

  // 写入 src/data/divisions.js
  const dataDir = resolve(ROOT, "src/data");
  await mkdir(dataDir, { recursive: true });
  const divisionsJs = `// Auto-generated by scripts/fetch-geojson.mjs — do not edit manually
export const divisions = ${JSON.stringify(divisionsData, null, 2)};

export const PROVINCE_NAMES = ${JSON.stringify(provinceNames, null, 2)};
`;
  await writeFile(resolve(dataDir, "divisions.js"), divisionsJs);
  console.log(`Divisions data: ${divisionsData.length} entries`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
